export const goalData = [
	{
		goalId: 1,
		title: "Complete Project A",
		description:
			"Finish all tasks related to Project A. This project involves developing a new mobile app for a client in the healthcare industry. It includes frontend and backend development, user interface design, and integration with third-party APIs. The goal is to complete the project by November 10, 2023.",
		date: "2023-11-10",
		priority: "high",
	},
	{
		goalId: 2,
		title: "Learn a New Language",
		description:
			"Begin learning a new programming language. I've decided to expand my skill set by diving into a new programming language, Python. My plan includes taking online courses, working on personal projects, and collaborating with other developers. The goal is to become proficient in Python by December 15, 2023.",
		date: "2023-12-15",
		priority: "medium",
	},
	{
		goalId: 3,
		title: "Exercise Regularly",
		description:
			"Develop a daily workout routine. It's important for my health and well-being to establish a consistent exercise routine. I will be doing a combination of cardio and strength training exercises for at least 30 minutes a day. My goal is to improve my fitness level and maintain this habit beyond November 20, 2023.",
		date: "2023-11-20",
		priority: "low",
	},
	{
		goalId: 4,
		title: "Read 10 Books",
		description:
			"Set a goal to read 10 books in the next year. I'm an avid reader and want to broaden my horizons by exploring a variety of genres, including fiction, non-fiction, and self-help books. I plan to read one book each month and finish this challenge by January 31, 2024.",
		date: "2024-01-31",
		priority: "medium",
	},
	{
		goalId: 5,
		title: "Travel to Europe",
		description:
			"Plan a trip to explore Europe. I've always dreamed of visiting Europe to experience its rich history, culture, and beautiful landscapes. My trip will include visiting major cities like Paris, Rome, and Barcelona, as well as exploring the countryside. The target date for this adventure is May 5, 2024.",
		date: "2024-05-05",
		priority: "high",
	},
];

// Sample JSON data for tasks
export const tasksData = [
	{
		taskId: 1,
		title: "Complete Project A",
		description: "Finish all tasks related to Project A.",
		priority: "high",
		deadline: "2023-11-10",
		isActive: true,
		createdAt: "2023-10-20",
		goalId: 1,
	},
	{
		taskId: 2,
		title: "Learn a New Language",
		description: "Begin learning a new programming language.",
		priority: "medium",
		deadline: "2023-12-15",
		isActive: true,
		createdAt: "2023-11-01",
		goalId: 2,
	},
	{
		taskId: 3,
		title: "Exercise Regularly",
		description: "Develop a daily workout routine.",
		priority: "low",
		deadline: "2023-11-20",
		isActive: false,
		createdAt: "2023-10-25",
		goalId: 3,
	},
	{
		taskId: 4,
		title: "Read 10 Books",
		description: "Set a goal to read 10 books in the next year.",
		priority: "medium",
		deadline: "2024-01-31",
		isActive: true,
		createdAt: "2023-12-10",
		goalId: 4,
	},
	{
		taskId: 5,
		title: "Travel to Europe",
		description: "Plan a trip to explore Europe.",
		priority: "high",
		deadline: "2024-05-05",
		isActive: true,
		createdAt: "2023-11-30",
		goalId: 5,
	},
	{
		taskId: 6,
		title: "Research project scope",
		description: "Gather information and define project A scope",
		priority: "High",
		deadline: "2023-11-10",
		isActive: true,
		createdAt: "2023-11-08",
		goalId: 1,
	},
	{
		taskId: 7,
		title: "Design project A architecture",
		description: "Create the architectural design for project A",
		priority: "High",
		deadline: "2023-11-15",
		isActive: true,
		createdAt: "2023-11-08",
		goalId: 1,
	},
	{
		taskId: 8,
		title: "Learn basic vocabulary",
		description: "Start with basic vocabulary in the new language",
		priority: "Medium",
		deadline: "2023-11-30",
		isActive: true,
		createdAt: "2023-11-10",
		goalId: 2,
	},
	{
		taskId: 9,
		title: "Cardio workout",
		description: "Do cardio exercises for 30 minutes daily",
		priority: "High",
		deadline: "2023-12-31",
		isActive: true,
		createdAt: "2023-11-15",
		goalId: 3,
	},
	{
		taskId: 10,
		title: "Read a science fiction book",
		description: "Explore a new science fiction book",
		priority: "Medium",
		deadline: "2023-12-31",
		isActive: true,
		createdAt: "2023-11-20",
		goalId: 4,
	},
];

// Sample JSON data for todos
export const todosData = [
	{
		todoId: 1,
		title: "Complete Project A - Task 1",
		priority: "high",
		createdAt: "2023-10-25",
		taskId: 1,
	},
	{
		todoId: 2,
		title: "Complete Project A - Task 2",
		priority: "medium",
		createdAt: "2023-10-26",
		taskId: 1,
	},
	{
		todoId: 3,
		title: "Learn Python Basics",
		priority: "medium",
		createdAt: "2023-11-05",
		taskId: 2,
	},
	{
		todoId: 4,
		title: "Morning Jog",
		priority: "low",
		createdAt: "2023-10-30",
		taskId: 3,
	},
	{
		todoId: 5,
		title: "Read 'The Great Gatsby'",
		priority: "high",
		createdAt: "2023-11-10",
		taskId: 4,
	},
];
