import "@/app/globals.scss";
import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import SessionProvider from "./SessionProvider";

export const metadata: Metadata = {
  title: "Revamp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="dark flex ">
          <SessionProvider>{children}</SessionProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
