import "@/app/globals.scss";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Timer",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="dark">{children}</body>
    </html>
  );
}
